### ISSUE TITLE
--deps doesn't note which dep. is optional

### ISSUE THREAD

**Issue by museun** [museun/whatfeatures#18]
example:
>whatfeatures tui -d
```
tui/0.6.2
  features
    default: termion
    curses: easycurses, pancurses
  dependencies
    normal
      bitflags             = ^1.0
      cassowary            = ^0.3
      crossterm            = ^0.9
      easycurses           = ^0.12.2
      either               = ^1.5
      itertools            = ^0.8
      log                  = ^0.4
      pancurses            = ^0.16.1
      rustbox              = ^0.11
      termion              = ^1.5
      unicode-segmentation = ^1.2
      unicode-width        = ^0.1
    dev
      failure              = ^0.1
      rand                 = ^0.6
      stderrlog            = ^0.4
      structopt            = ^0.2
```

```toml
[dependencies]
bitflags = "1.0"
cassowary = "0.3"
itertools = "0.8"
log = "0.4"
either = "1.5"
unicode-segmentation = "1.2"
unicode-width = "0.1"
termion = { version = "1.5", optional = true }
rustbox = { version = "0.11", optional = true }
crossterm = { version = "^0.9", optional = true }
easycurses = { version = "0.12.2", optional = true }
pancurses = { version = "0.16.1", optional = true, features = ["win32a"] }

[dev-dependencies]
stderrlog = "0.4"
rand = "0.6"
failure = "0.1"
structopt = "0.2"
```

also, deps should show the features for the deps themselves.
